language: node_js
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "7"
install:
  - cp src/constants/config.js.example src/constants/config.js
  - yarn install
script:
  - npm run test
