// flow-typed signature: 9a631e00a982dac67edc4c169bdaf4fb
// flow-typed version: <<STUB>>/react-native-lock_v^0.4.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-lock' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
}
declare module 'react-native-lock/auth0-lock' {
  declare module.exports: any;
}
declare module 'react-native-lock/version' {
  declare module.exports: any;

  // Filename aliases
}
declare module 'react-native-lock/auth0-lock.js' {
  declare module.exports: $Exports<'react-native-lock/auth0-lock'>;
}
declare module 'react-native-lock/version.js' {
  declare module.exports: $Exports<'react-native-lock/version'>;
}
