// flow-typed signature: 19bdfb34a2aab37b15fd455fbc268b4c
// flow-typed version: <<STUB>>/react-native-image-progress_v^0.6.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-progress' {
  declare module.exports: any;

  /**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

  // Filename aliases
}
declare module 'react-native-image-progress/index' {
  declare module.exports: $Exports<'react-native-image-progress'>;
}
declare module 'react-native-image-progress/index.js' {
  declare module.exports: $Exports<'react-native-image-progress'>;
}
